# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: MyubuntuAgentPool

steps:
- script: echo "Hello World" > index.html
  displayName: 'Create index.html file'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: 'index.html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '23391da9-5b2e-429e-9289-9e4398f731bc' # Replace with your Azure subscription
    appType: webApp
    appName: 'twoerror' # Replace with your Azure Web App name
    package: '$(Build.ArtifactStagingDirectory)/index.html'
